### ISSUE TITLE
Annotate quit claim ($1, $100) deeds in front end.

### ISSUE THREAD

**Issue by ericrobskyhuntley** [mit-spatial-action/who-owns-mass-frontend#33]
Participants noted with some surprise recent transactions at values of $1, $100---I explained what a quit claim deed, but the app should do that too. Could preprocess, but seems like this is a good case for a simple conditional on the frontend.

**Comment by mchuttani18** [comment]
Pushed for review. For testing: 
 
676 MASSACHUSETTS AVENUE BOSTON MA = property with "unknown" sale price. 
59 EAST SPRINGFIELD STREET BOSTON MA = property with "low" sale price

**Comment by ericrobskyhuntley** [comment]
Donezo funzo!
