### ISSUE TITLE
Clear map marker when return to search 

### ISSUE THREAD

**Issue by mchuttani18** [mit-spatial-action/who-owns-mass-frontend#39]
Clicking "Return to Search" button should clear the map markers.

**Comment by mchuttani18** [comment]
Also possibly change tilt back to original pre-click to signal to the user to search again (enhancement)

**Comment by mchuttani18** [comment]
* Add a responsive line to clear layers when both the relevant state objects are undefined.

**Comment by ericrobskyhuntley** [comment]
Thanks! Looks good. Closed with #42
